import { createElement } from './framework.js'

export const div = (attrs, ...children) => createElement('div', attrs, ...children)
export const p = (attrs, ...children) => createElement('p', attrs, ...children)
export const strong = (attrs, ...children) => createElement('strong', attrs, ...children)
export const a = (attrs, ...children) => createElement('a', attrs, ...children)
export const ul = (attrs, ...children) => createElement('ul', attrs, ...children)
export const li = (attrs, ...children) => createElement('li', attrs, ...children)
export const h1 = (attrs, ...children) => createElement('h1', attrs, ...children)
export const h2 = (attrs, ...children) => createElement('h2', attrs, ...children)
export const h3 = (attrs, ...children) => createElement('h3', attrs, ...children)
export const h4 = (attrs, ...children) => createElement('h4', attrs, ...children)
export const h5 = (attrs, ...children) => createElement('h5', attrs, ...children)
export const h6 = (attrs, ...children) => createElement('h6', attrs, ...children)
export const span = (attrs, ...children) => createElement('span', attrs, ...children)
export const img = (attrs) => createElement('img', attrs)
export const button = (attrs, ...children) => createElement('button', attrs, ...children)
export const input = (attrs) => createElement('input', attrs)
export const form = (attrs, ...children) => createElement('form', attrs, ...children)
export const label = (attrs, ...children) => createElement('label', attrs, ...children)
export const textarea = (attrs, ...children) => createElement('textarea', attrs, ...children)
export const select = (attrs, ...children) => createElement('select', attrs, ...children)
export const option = (attrs, ...children) => createElement('option', attrs, ...children)
export const table = (attrs, ...children) => createElement('table', attrs, ...children)
export const thead = (attrs, ...children) => createElement('thead', attrs, ...children)
export const tbody = (attrs, ...children) => createElement('tbody', attrs, ...children)
export const tr = (attrs, ...children) => createElement('tr', attrs, ...children)
export const th = (attrs, ...children) => createElement('th', attrs, ...children)
export const td = (attrs, ...children) => createElement('td', attrs, ...children)
export const nav = (attrs, ...children) => createElement('nav', attrs, ...children)
export const header = (attrs, ...children) => createElement('header', attrs, ...children)
export const footer = (attrs, ...children) => createElement('footer', attrs, ...children)
export const main = (attrs, ...children) => createElement('main', attrs, ...children)
export const section = (attrs, ...children) => createElement('section', attrs, ...children)
export const article = (attrs, ...children) => createElement('article', attrs, ...children)
export const aside = (attrs, ...children) => createElement('aside', attrs, ...children)
